Repository eduardconstantin/azure-cloud-exams, pull requests merged in 2023-10, with the labels that each got.

#61 Increases the Size of Questions of Practice mode
  pages/api/og.tsx
Labels: enhancement, hacktoberfest

#65 Implement exam quiz
  components/ExamQuizForm.tsx
  components/ExamResult.tsx
  pages/exam/index.tsx
Labels: enhancement, hacktoberfest

#68 feat: add prettier and husky
  .husky/pre-commit
  .lintstagedrc
  .prettierrc
  package-lock.json
  package.json
Labels: enhancement, hacktoberfest

#69 Added Missing details in Exam Complition UI
  components/ExamResult.tsx
Labels: enhancement, hacktoberfest

#78 Fix/completion screen UI
  components/ExamQuizForm.tsx
  components/ExamResult.tsx
  pages/exam/index.tsx
Labels: enhancement, hacktoberfest

#74 Change in UI
  components/Footer.tsx
  components/QuizForm.tsx
  components/SelectionInput.tsx
  components/TopNav.tsx
  pages/api/og.tsx
  pages/index.tsx
  pages/practice/index.tsx
Labels: enhancement, hacktoberfest

#79 Fixed text overflow for larger screens
  components/ExamLink.tsx
Labels: enhancement, hacktoberfest

#84 Fix question index numbering
  components/QuizForm.tsx
  pages/exam/index.tsx
  pages/practice/index.tsx
Labels: enhancement, hacktoberfest

#87 Fix: hide back button for first question
  components/QuizForm.tsx
Labels: enhancement, good first issue

#82 Features/feature skipped question
  components/ExamQuizForm.tsx
  pages/exam/index.tsx
  utils/Queue.ts
Labels: enhancement, hacktoberfest

#88 Fix reveal answer remains selected
  components/QuizForm.tsx
Labels: enhancement, hacktoberfest

#92 Fix/elapsed time
  pages/exam/index.tsx
Labels: enhancement, hacktoberfest

#93 Fix console errors
  components/QuizForm.tsx
  components/SelectionInput.tsx
Labels: bug
